version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/server
    binary: sponsorkit
    ldflags:
      - -s -w
      - -X main.Mode=release

archives:
  - id: default
    formats:
      - tar.gz
    name_template: 'sponsorkit_{{ .Tag }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    files: []

upx:
  - enabled: true
    ids:
      - linux
    compress: best
    lzma: true

checksum:
  name_template: "sponsorkit_{{ .Tag }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
