"use client";

import { useEffect } from "react";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer, toast } from "react-toastify";

import { app } from "./store";

import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    app.onTip((msg) => {
      const { text } = msg;
      toast(
        <div className="p-4">
          {text.map((t, i) => {
            return <div key={i}>{t}</div>;
          })}
        </div>,
        {
          autoClose: 1000,
        }
      );
    });
  }, []);

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
        <ToastContainer theme="dark" />
      </body>
    </html>
  );
}
